# Managed by oooconf.
# Add portable Yazi defaults here as they are adopted.
[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*/"
run   = "git"
group = "git"


[plugin]
prepend_previewers = [
  { url = "*.md",     run = 'faster-piper --rely-on-preloader' },
  { url = "*.tar*",   run = 'faster-piper --rely-on-preloader --format=url' },
  { url = "*.txt.gz", run = 'faster-piper --rely-on-preloader' },
  { url = "*.csv",    run = 'faster-piper --rely-on-preloader' },
  { url = "*/",       run = 'faster-piper --rely-on-preloader' },
]

prepend_preloaders = [
  { url = "*.md",     run = 'faster-piper -- glow -w=$w -s=gruvbox -- "$1"' },
  { url = "*.tar*",   run = 'faster-piper -- tar tf "$1"' },
  { url = "*.txt.gz", run = 'faster-piper -- gzip -dc "$1"' },
  { url = "*.csv",    run = 'faster-piper -- bat -p --color=always -- "$1"' },
  { url = "*/",       run = 'faster-piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
]