print("In `setup.ps1`:")
print("```powershell")
print("function Get-EditDistance {")
print("    param([string]$Left, [string]$Right)")
print("    $rows = $Left.Length + 1")
print("    $cols = $Right.Length + 1")
print("    $dist = New-Object 'int[,]' $rows, $cols")
print("    ...")
print("}```")
print("We'll replace it with the one from `ooodnakov.ps1`:")
print("```powershell")
print("function Get-EditDistance {")
print("    param([string]$Left, [string]$Right)")
print("    $rightLength = $Right.Length")
print("    $previous = New-Object int[] ($rightLength + 1)")
print("    for ($j = 0; $j -le $rightLength; $j++) { $previous[$j] = $j }")
print("    for ($i = 1; $i -le $Left.Length; $i++) {")
print("        $current = New-Object int[] ($rightLength + 1)")
print("        $current[0] = $i")
print("        $leftChar = $Left.Substring($i - 1, 1)")
print("        for ($j = 1; $j -le $rightLength; $j++) {")
print("            $rightChar = $Right.Substring($j - 1, 1)")
print("            $cost = if ($leftChar -ceq $rightChar) { 0 } else { 1 }")
print("            $deletion = $previous[$j] + 1")
print("            $insertion = $current[$j - 1] + 1")
print("            $substitution = $previous[$j - 1] + $cost")
print("            $current[$j] = [Math]::Min([Math]::Min($deletion, $insertion), $substitution)")
print("        }")
print("        $previous = $current")
print("    }")
print("    return $previous[$rightLength]")
print("}")
print("```")
