# PowerShell argument completions for oooconf
# Generated by scripts/generate_oooconf_completions.py; edit scripts/oooconf-cli-spec.toml instead.
# This file is automatically loaded by the managed PowerShell profile via common.ps1

function Get-OooconfCompletions {
    param($wordToComplete, $commandAst, $cursorPosition)

    $OooconfCommands = @(
        'bootstrap',
        'install',
        'deps',
        'update',
        'doctor',
        'dry-run',
        'delete',
        'remove',
        'lock',
        'update-pins',
        'completions',
        'agents',
        'secrets',
        'shell',
        'color',
        'version',
        'check',
        'preview',
        'upgrade',
        'komorebi',
        'wm',
        'help',
        'minimal'
    )

    $OooconfGlobalOptions = @(
        '-C',
        '--repo-root',
        '--print-repo-root',
        '-h',
        '--help',
        '-n',
        '--dry-run',
        '--yes-optional',
        '-V',
        '--version'
    )

    $OooconfGlobalOptionsWithArgs = @(
        '-C',
        '--repo-root'
    )

    $OooconfAliases =
    @{
        'check' = 'doctor'
        'preview' = 'dry-run'
        'upgrade' = 'update'
    }

    $OooconfNodes = @{
        'agents' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('detect', 'sync', 'doctor', 'mcp', 'status', 'rtk', 'provider', 'update', 'install', 'install-scripts-build', 'skills')
            OptionValues = @{
            }
        }
        'agents:detect' = @{
            Options = @('--repo-root', '--config', '--json')
            OptionsWithArgs = @('--repo-root', '--config')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:doctor' = @{
            Options = @('--repo-root', '--config', '--strict-config-paths')
            OptionsWithArgs = @('--repo-root', '--config')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:install' = @{
            Options = @('--repo-root', '--config', '--all', '--missing', '--check')
            OptionsWithArgs = @('--repo-root', '--config')
            Values = @('codex', 'claude', 'gemini', 'qwen', 'cursor-agent', 'opencode', 'aider')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:install-scripts-build' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:mcp' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('sync', 'status', 'add')
            OptionValues = @{
            }
        }
        'agents:mcp:add' = @{
            Options = @('--name', '--json', '--multi', '--preview', '--sync-now', '--check')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:mcp:status' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:mcp:sync' = @{
            Options = @('--check')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:provider' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('sync')
            OptionValues = @{
            }
        }
        'agents:provider:sync' = @{
            Options = @('--check', '--materialize-secrets', '--region')
            OptionsWithArgs = @('--region')
            Values = @()
            Subcommands = @()
            OptionValues = @{
                '--region' = @('global', 'china')
            }
        }
        'agents:rtk' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('init')
            OptionValues = @{
            }
        }
        'agents:rtk:init' = @{
            Options = @('--check')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:skills' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('sync', 'view', 'add')
            OptionValues = @{
            }
        }
        'agents:skills:add' = @{
            Options = @('--agent', '--sync-now', '--check')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:skills:sync' = @{
            Options = @('--check')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:skills:view' = @{
            Options = @('--check', '--json')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:status' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:sync' = @{
            Options = @('--repo-root', '--config', '--check', '--global', '--materialize-secrets')
            OptionsWithArgs = @('--repo-root', '--config')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'agents:update' = @{
            Options = @('--repo-root', '--config', '--check')
            OptionsWithArgs = @('--repo-root', '--config')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'bootstrap' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'check' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'color' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('status', 'list', 'dark', 'light', 'default', 'catppuccin', 'gruvbox', 'nord', 'tokyonight', 'noctalia')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'completions' = @{
            Options = @('--dry-run')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'delete' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'deps' = @{
            Options = @('--dry-run', '--yes-optional', '-h', '--help')
            OptionsWithArgs = @()
            Values = @('wget', 'git', 'wezterm', 'oh-my-posh', 'posh-git', 'psfzf', 'choco', 'gsudo', 'rg', 'fd', 'zsh', 'direnv', 'fzf', 'bat', 'delta', 'glow', 'gum', 'zoxide', 'q', 'eza', 'yazi', 'ffmpeg', 'jq', 'p7zip', 'poppler', 'fc-cache', 'cargo', 'dua', 'nvim', 'tree-sitter', 'k', 'python3', 'lazygit', 'lazydocker', 'docker', 'impala', 'bluetui', 'uv', 'bw', 'node', 'pnpm', 'rtk', 'imagemagick', 'ghostscript', 'luarocks', 'tectonic', 'mermaid-cli', 'zig', 'neovim-node', 'neovim-python', 'fastfetch', 'btop', 'cava', 'blackhole-2ch', 'glazewm', 'zebar', 'overline-zebar')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'doctor' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'dry-run' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'help' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'install' = @{
            Options = @('--dry-run', '--yes-optional', '-h', '--help')
            OptionsWithArgs = @()
            Values = @('wget', 'git', 'wezterm', 'oh-my-posh', 'posh-git', 'psfzf', 'choco', 'gsudo', 'rg', 'fd', 'zsh', 'direnv', 'fzf', 'bat', 'delta', 'glow', 'gum', 'zoxide', 'q', 'eza', 'yazi', 'ffmpeg', 'jq', 'p7zip', 'poppler', 'fc-cache', 'cargo', 'dua', 'nvim', 'tree-sitter', 'k', 'python3', 'lazygit', 'lazydocker', 'docker', 'impala', 'bluetui', 'uv', 'bw', 'node', 'pnpm', 'rtk', 'imagemagick', 'ghostscript', 'luarocks', 'tectonic', 'mermaid-cli', 'zig', 'neovim-node', 'neovim-python', 'fastfetch', 'btop', 'cava', 'blackhole-2ch', 'glazewm', 'zebar', 'overline-zebar')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'komorebi' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'lock' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'minimal' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'preview' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'remove' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'secrets' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('login', 'unlock', 'sync', 'doctor', 'list', 'ls', 'status', 'logout', 'add', 'remove', 'rm', 'del')
            OptionValues = @{
            }
        }
        'secrets:add' = @{
            Options = @('--template')
            OptionsWithArgs = @('--template')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'secrets:del' = @{
            Options = @('--template')
            OptionsWithArgs = @('--template')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'secrets:doctor' = @{
            Options = @('--backend', '--template')
            OptionsWithArgs = @('--backend', '--template')
            Values = @()
            Subcommands = @()
            OptionValues = @{
                '--backend' = @('bw')
            }
        }
        'secrets:list' = @{
            Options = @('--template', '--resolved', '--backend')
            OptionsWithArgs = @('--template', '--backend')
            Values = @()
            Subcommands = @()
            OptionValues = @{
                '--backend' = @('bw')
            }
        }
        'secrets:login' = @{
            Options = @('--server', '--method', '--client-id', '--client-secret')
            OptionsWithArgs = @('--method')
            Values = @()
            Subcommands = @()
            OptionValues = @{
                '--method' = @('auto', 'password', 'apikey')
            }
        }
        'secrets:logout' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'secrets:ls' = @{
            Options = @('--template', '--resolved', '--backend')
            OptionsWithArgs = @('--template', '--backend')
            Values = @()
            Subcommands = @()
            OptionValues = @{
                '--backend' = @('bw')
            }
        }
        'secrets:remove' = @{
            Options = @('--template')
            OptionsWithArgs = @('--template')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'secrets:rm' = @{
            Options = @('--template')
            OptionsWithArgs = @('--template')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'secrets:status' = @{
            Options = @('--template')
            OptionsWithArgs = @('--template')
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'secrets:sync' = @{
            Options = @('--backend', '--template', '--dry-run', '--force')
            OptionsWithArgs = @('--backend', '--template')
            Values = @()
            Subcommands = @()
            OptionValues = @{
                '--backend' = @('bw')
            }
        }
        'secrets:unlock' = @{
            Options = @('--shell', '--raw')
            OptionsWithArgs = @('--shell')
            Values = @()
            Subcommands = @()
            OptionValues = @{
                '--shell' = @('sh', 'zsh', 'bash', 'pwsh', 'fish')
            }
        }
        'shell' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('status', 'prompt', 'prompt-style', 'forgit-aliases', 'typo-handling', 'psfzf-tab', 'psfzf-git', 'auto-uv-env')
            OptionValues = @{
            }
        }
        'shell:auto-uv-env' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('enabled', 'quiet', 'status')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'shell:forgit-aliases' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('plain', 'forgit', 'status')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'shell:prompt' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('p10k', 'ohmyposh', 'status')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'shell:prompt-style' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('verbose', 'concise', 'status')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'shell:psfzf-git' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('enabled', 'disabled', 'status')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'shell:psfzf-tab' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('enabled', 'disabled', 'status')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'shell:status' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'shell:typo-handling' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('silent', 'suggest', 'help', 'status')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'update' = @{
            Options = @('--dry-run', '--yes-optional', '-h', '--help')
            OptionsWithArgs = @()
            Values = @('wget', 'git', 'wezterm', 'oh-my-posh', 'posh-git', 'psfzf', 'choco', 'gsudo', 'rg', 'fd', 'zsh', 'direnv', 'fzf', 'bat', 'delta', 'glow', 'gum', 'zoxide', 'q', 'eza', 'yazi', 'ffmpeg', 'jq', 'p7zip', 'poppler', 'fc-cache', 'cargo', 'dua', 'nvim', 'tree-sitter', 'k', 'python3', 'lazygit', 'lazydocker', 'docker', 'impala', 'bluetui', 'uv', 'bw', 'node', 'pnpm', 'rtk', 'imagemagick', 'ghostscript', 'luarocks', 'tectonic', 'mermaid-cli', 'zig', 'neovim-node', 'neovim-python', 'fastfetch', 'btop', 'cava', 'blackhole-2ch', 'glazewm', 'zebar', 'overline-zebar')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'update-pins' = @{
            Options = @('--apply')
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'upgrade' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'version' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('komorebi', 'glazewm')
            Subcommands = @('status', 'set', 'start', 'stop', 'reload', 'bar', 'komorebi')
            OptionValues = @{
            }
        }
        'wm:bar' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @('set', 'zebar-config', 'stop', 'start', 'reload')
            OptionValues = @{
            }
        }
        'wm:bar:reload' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:bar:set' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('zebar', 'yabs')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:bar:start' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:bar:stop' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:bar:zebar-config' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:komorebi' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:reload' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:set' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @('komorebi', 'glazewm')
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:start' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:status' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
        'wm:stop' = @{
            Options = @()
            OptionsWithArgs = @()
            Values = @()
            Subcommands = @()
            OptionValues = @{
            }
        }
    }

    $elements = $commandAst.CommandElements
    $tokens = @()
    for ($i = 0; $i -lt $elements.Count; $i++) {
        $element = $elements[$i]
        if ($element -is [System.Management.Automation.Language.CommandParameterAst]) {
            $val = "-$($element.ParameterName)"
            if ($val -eq $wordToComplete -and $i -eq ($elements.Count - 1)) { break }
            $tokens += $val
        } elseif ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
            $val = $element.Value
            if ($val -eq $wordToComplete -and $i -eq ($elements.Count - 1)) { break }
            $tokens += $val
        }
    }

    $commandIndex = -1
    for ($i = 0; $i -lt $tokens.Length; $i++) {
        if ($tokens[$i] -match '(^|[\\\\/])(oooconf|o)(\.ps1|\.cmd)?$') {
            $commandIndex = $i
            break
        }
    }
    if ($commandIndex -eq -1) { return @() }

    $commandName = $null
    $commandPos = -1
    for ($i = $commandIndex + 1; $i -lt $tokens.Length; $i++) {
        $token = $tokens[$i]
        if ($token -in $OooconfGlobalOptionsWithArgs) { $i++; continue }
        if ($token -in $OooconfCommands) { $commandName = $token; $commandPos = $i; break }
        if ($token -notlike '-*') { break }
    }

    if ($null -eq $commandName) {
        return ($OooconfCommands + $OooconfGlobalOptions) | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
    }

    if ($OooconfAliases.ContainsKey($commandName)) { $commandName = $OooconfAliases[$commandName] }
    $path = @($commandName)
    $nodeKey = $commandName
    $lastNodeKey = $nodeKey
    for ($i = $commandPos + 1; $i -lt $tokens.Length; $i++) {
        $node = if ($OooconfNodes.ContainsKey($nodeKey)) { $OooconfNodes[$nodeKey] } else { $null }
        if ($null -eq $node) { break }
        $token = $tokens[$i]
        if ($token -like '-*') {
            if (($token -in $OooconfGlobalOptionsWithArgs) -or ($token -in $node.OptionsWithArgs)) { $i++ }
            continue
        }
        if ($token -in $node.Subcommands) {
            $path += $token
            $nodeKey = ($path -join ':')
            $lastNodeKey = $nodeKey
        }
    }

    $currentNode = if ($OooconfNodes.ContainsKey($lastNodeKey)) { $OooconfNodes[$lastNodeKey] } else { $null }
    if ($null -eq $currentNode) { return @() }
    $previousToken = if ($tokens.Length -gt 0) { $tokens[-1] } else { '' }
    if ($currentNode.OptionValues.ContainsKey($previousToken)) {
        $completions = $currentNode.OptionValues[$previousToken]
    } else {
        $completions = $currentNode.Options + $currentNode.Subcommands + $currentNode.Values
    }

    return $completions | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }
}

@('oooconf', 'oooconf.ps1', 'oooconf.cmd', 'o', 'o.ps1', 'o.cmd') | ForEach-Object {
    Register-ArgumentCompleter -Native -CommandName $_ -ScriptBlock {
        param($wordToComplete, $commandAst, $cursorPosition)
        Get-OooconfCompletions -wordToComplete $wordToComplete -commandAst $commandAst -cursorPosition $cursorPosition
    }
}
