"""Contract tests that keep the CLI spec, dispatchers, and generated docs aligned."""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts/cli"))

from generate_cli_reference import render  # noqa: E402
from oooconf_cli_spec import Command, load_cli_spec  # noqa: E402

SPEC_PATH = REPO_ROOT / "scripts/cli/oooconf-cli-spec.toml"
BASH_ENTRYPOINT = REPO_ROOT / "scripts/setup/ooodnakov.sh"
POWERSHELL_ENTRYPOINT = REPO_ROOT / "scripts/setup/ooodnakov.ps1"


def walk_leaves(commands: dict[str, Command], prefix: tuple[str, ...] = ()):
    for name, command in commands.items():
        path = (*prefix, name)
        if command.subcommands:
            yield from walk_leaves(command.subcommands, path)
        else:
            yield path, command


def bash_dispatch_commands() -> set[str]:
    text = BASH_ENTRYPOINT.read_text(encoding="utf-8").split('case "$command" in', 1)[1]
    return set(re.findall(r"^  ([a-z][a-z0-9-]*)\)$", text, re.MULTILINE))


def powershell_dispatch_commands() -> set[str]:
    text = POWERSHELL_ENTRYPOINT.read_text(encoding="utf-8").split("switch ($command) {", 1)[1]
    return set(re.findall(r'^    "([a-z][a-z0-9-]*)" \{$', text, re.MULTILINE))


def test_every_leaf_has_a_handler_on_each_declared_platform() -> None:
    spec = load_cli_spec(SPEC_PATH)
    dispatchers = {
        "linux": bash_dispatch_commands(),
        "macos": bash_dispatch_commands(),
        "windows": powershell_dispatch_commands(),
    }
    parser_commands = {"help", "version"}

    for path, command in walk_leaves(spec.commands):
        assert command.handler_id
        target = command.alias_for or path[0]
        if command.alias_for:
            target = spec.commands[command.alias_for].name
        for platform in command.platforms:
            assert target in dispatchers[platform] or target in parser_commands, (
                f"{command.handler_id} has no {platform} handler for {' '.join(path)}"
            )


def test_dispatchers_expose_no_undocumented_public_commands() -> None:
    spec = load_cli_spec(SPEC_PATH)
    aliases = set(spec.aliases())
    parser_commands = {"help", "version"}
    expected_bash = (
        {name for name, command in spec.commands.items() if "linux" in command.platforms} - aliases - parser_commands
    )
    expected_windows = (
        {name for name, command in spec.commands.items() if "windows" in command.platforms} - aliases - parser_commands
    )

    assert bash_dispatch_commands() == expected_bash
    assert powershell_dispatch_commands() == expected_windows


def test_dispatchers_expose_no_undocumented_global_options() -> None:
    spec = load_cli_spec(SPEC_PATH)
    documented = set(spec.global_options)
    bash_parser = BASH_ENTRYPOINT.read_text(encoding="utf-8").split('if [ -z "$command" ]', 1)[0]
    ps_parser = POWERSHELL_ENTRYPOINT.read_text(encoding="utf-8").split("if (-not $command)", 1)[0]
    bash_public: set[str] = set()
    for pattern in re.findall(r"^    ([^\n)]*)\)", bash_parser, re.MULTILINE):
        bash_public.update(item for item in pattern.split("|") if re.fullmatch(r"--?[A-Za-z][A-Za-z0-9-]*", item))
    ps_options = set(re.findall(r'"(--?[A-Za-z][A-Za-z0-9-]*)"', ps_parser))

    # Only parser case/switch labels are public options; flags passed to internal
    # subprocesses are deliberately excluded.
    assert bash_public == documented
    assert ps_options == documented


def test_generated_cli_reference_is_current_and_examples_remain_hand_authored() -> None:
    spec = load_cli_spec(SPEC_PATH)
    reference = (REPO_ROOT / "docs/cli-reference.md").read_text(encoding="utf-8")
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

    assert reference == render(spec)
    assert "Generated by scripts/cli/generate_cli_reference.py" in reference
    assert "```" not in reference
    assert "```bash" in readme
    assert "oooconf plan" in readme
