#!/usr/bin/env python3
"""Generate the public oooconf command reference from the canonical CLI spec."""

from __future__ import annotations

from pathlib import Path

from oooconf_cli_spec import CliSpec, Command, load_cli_spec

REPO_ROOT = Path(__file__).resolve().parents[2]
SPEC_PATH = REPO_ROOT / "scripts/cli/oooconf-cli-spec.toml"
OUTPUT_PATH = REPO_ROOT / "docs/cli-reference.md"


def walk(commands: dict[str, Command], prefix: tuple[str, ...] = ()) -> list[tuple[tuple[str, ...], Command]]:
    nodes: list[tuple[tuple[str, ...], Command]] = []
    for name, command in commands.items():
        path = (*prefix, name)
        nodes.append((path, command))
        nodes.extend(walk(command.subcommands, path))
    return nodes


def render(spec: CliSpec) -> str:
    lines = [
        "# oooconf CLI Reference",
        "",
        "<!-- Generated by scripts/cli/generate_cli_reference.py; do not edit. -->",
        "",
        f"CLI specification schema version: `{spec.schema_version}` (minimum reader: `{spec.minimum_reader_version}`).",
        "",
        "Operational examples remain hand-authored in `README.md` and the platform-native `oooconf help` output.",
        "",
        "## Global options",
        "",
        "| Option | Description |",
        "|---|---|",
    ]
    lines.extend(f"| `{option}` | {description} |" for option, description in spec.global_options.items())
    lines.extend(
        [
            "",
            "## Commands",
            "",
            "| Command | Description | Platforms | Handler ID | Options |",
            "|---|---|---|---|---|",
        ]
    )
    for path, command in walk(spec.commands):
        options = ", ".join(f"`{item}`" for item in command.options) or "—"
        platforms = ", ".join(command.platforms)
        lines.append(
            f"| `oooconf {' '.join(path)}` | {command.description} | {platforms} | `{command.handler_id}` | {options} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT_PATH.write_text(render(load_cli_spec(SPEC_PATH)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
