# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                  Layout and Behavior Configuration           ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


general {
    gaps_in = 5
    gaps_out = 10
    border_size = 3
    col.active_border = $noctalia_primary
    col.inactive_border = $noctalia_surface_variant
    layout = dwindle

    snap {
        enabled = true
    }
}

group {
    col.border_active = $noctalia_primary
    col.border_inactive = $noctalia_surface_variant
    col.border_locked_active = $noctalia_secondary
    col.border_locked_inactive = $noctalia_outline

    groupbar {
        font_family = "Fira Sans"
        text_color = $noctalia_surface
        col.active = $noctalia_primary
        col.inactive = $noctalia_surface_variant
        col.locked_active = $noctalia_secondary
        col.locked_inactive = $noctalia_outline
    }
}

misc {
    font_family = "Fira Sans"
    splash_font_family = "Fira Sans"
    disable_hyprland_logo = true
    col.splash = $noctalia_primary
    background_color = $noctalia_surface
    enable_swallow = true
    swallow_regex = ^(org.wezfurlong.wezterm|wezterm|kitty|Alacritty)$
    focus_on_activate = false
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    vrr = 2
}

render {
   direct_scanout = true
}

dwindle {
    special_scale_factor = 0.8
    preserve_split = true
}

master {
    new_status = master
    special_scale_factor = 0.8
}

# Touchpad gestures.
gesture = 4, horizontal, workspace
gesture = 3, down, close
gesture = 3, up, fullscreen
gesture = 3, left, float
