#!/usr/bin/env python3
"""Generate oooconf completion scripts from tracked command/dependency catalogs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from oooconf_cli_spec import CliSpec, Command, load_cli_spec, shell_safe_name
from read_optional_deps import load_deps

REPO_ROOT = Path(__file__).resolve().parent.parent
COMMANDS_FILE = REPO_ROOT / "scripts" / "oooconf-commands.txt"
CLI_SPEC_FILE = REPO_ROOT / "scripts" / "oooconf-cli-spec.toml"
ZSH_OUTPUT = REPO_ROOT / "home/.config/ooodnakov/zsh/completions/_oooconf"
POWERSHELL_OUTPUT = REPO_ROOT / "home/.config/ooodnakov/completions/oooconf-completions.ps1"


@dataclass(frozen=True)
class CompletionNode:
    path: tuple[str, ...]
    command: Command
    options: dict[str, str]
    completers: dict[str, str]
    values: dict[str, str]
    option_values: dict[str, dict[str, str]]

    @property
    def key(self) -> str:
        return ":".join(self.path)

    @property
    def function_name(self) -> str:
        return "_oooconf_" + "_".join(shell_safe_name(part) for part in self.path)


def load_commands(path: Path) -> list[str]:
    commands: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        commands.append(line)

    if "help" not in commands:
        commands.append("help")

    return commands


def load_dependency_definitions() -> dict[str, dict[str, str]]:
    deps_data = load_deps()["deps"]
    deps_keys = {
        dep.get("key", ""): dep.get("description", "") or dep.get("key", "") for dep in deps_data if dep.get("key")
    }
    return {"deps_keys": deps_keys}


def unique_preserving_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        result.append(item)
    return result


def quote_zsh(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "'\\''")


def quote_ps(value: str) -> str:
    return value.replace("'", "''")


def zsh_pattern(value: str) -> str:
    return value.replace("\\", "\\\\").replace(")", "\\)").replace("|", "\\|")


def zsh_describe_array(name: str, values: dict[str, str], lines: list[str]) -> None:
    lines.append(f"  local -a {name}")
    lines.append(f"  {name}=(")
    for key, description in values.items():
        lines.append(f"    '{quote_zsh(key)}:{quote_zsh(description)}'")
    lines.append("  )")


def zsh_value_choices(values: dict[str, str]) -> str:
    return " ".join(quote_zsh(value) for value in values)


def zsh_option_spec(option: str, description: str, completer: str | None, value_set: dict[str, str] | None) -> str:
    spec = f"{option}[{description}]"
    if value_set is not None:
        spec += f":value:({zsh_value_choices(value_set)})"
    elif completer:
        spec += f":value:{completer}"
    return spec


def resolve_values(command: Command, spec: CliSpec) -> dict[str, str]:
    values = dict(command.values)
    if command.value_set:
        values.update(spec.definition_values(command.value_set))
    return values


def resolve_option_values(command: Command, spec: CliSpec) -> dict[str, dict[str, str]]:
    return {option: spec.definition_values(value_set) for option, value_set in command.option_value_sets.items()}


def walk_commands(commands: dict[str, Command], spec: CliSpec, prefix: tuple[str, ...] = ()) -> list[CompletionNode]:
    nodes: list[CompletionNode] = []
    for name, command in commands.items():
        path = (*prefix, name)
        nodes.append(
            CompletionNode(
                path=path,
                command=command,
                options=command.options,
                completers=command.completers,
                values=resolve_values(command, spec),
                option_values=resolve_option_values(command, spec),
            )
        )
        nodes.extend(walk_commands(command.subcommands, spec, path))
    return nodes


def command_order(commands: list[str], spec: CliSpec) -> list[str]:
    return unique_preserving_order([*commands, *spec.commands.keys()])


def render_zsh(commands: list[str], spec: CliSpec) -> str:
    commands = command_order(commands, spec)
    nodes = walk_commands(spec.commands, spec)
    node_map = {node.path: node for node in nodes}
    aliases = spec.aliases()

    lines: list[str] = []
    lines.append("#compdef oooconf o")
    lines.append("# Generated by scripts/generate_oooconf_completions.py; edit scripts/oooconf-cli-spec.toml instead.")
    lines.append("")

    top_commands = {name: spec.commands.get(name, Command(name=name)).description for name in commands}
    zsh_describe_array("_oooconf_commands", top_commands, lines)
    zsh_describe_array("_oooconf_global_opts", spec.global_options, lines)
    lines.append("")

    for alias, target in aliases.items():
        alias_node = node_map.get((alias,))
        target_node = node_map.get((target,))
        if alias_node and target_node:
            lines.append(f'{alias_node.function_name}() {{ {target_node.function_name} "$@" }}')
    if aliases:
        lines.append("")

    for node in nodes:
        if node.command.alias_for:
            continue
        render_zsh_node(node, lines)
        lines.append("")

    lines.append("_oooconf_main() {")
    lines.append("  local context state line")
    lines.append("  typeset -A opt_args")
    lines.append("  _arguments -C \\")
    for option, description in spec.global_options.items():
        completer = spec.global_completers.get(option)
        lines.append(f"    '{quote_zsh(zsh_option_spec(option, description, completer, None))}' \\")
    lines.append("    '1:command:->command' \\")
    lines.append("    '*::arg:->args'")
    lines.append("")
    lines.append("  case $state in")
    lines.append("    command)")
    lines.append("      _describe -t commands 'oooconf command' _oooconf_commands")
    lines.append("      ;;")
    lines.append("    args)")
    lines.append("      local command_name i")
    lines.append("      for (( i = 2; i < CURRENT; i++ )); do")
    lines.append('        case "$words[i]" in')
    lines.append("          -C|--repo-root) (( i++ )) ;;")
    lines.append("          -*) ;;")
    lines.append('          *) command_name="$words[i]"; break ;;')
    lines.append("        esac")
    lines.append("      done")
    lines.append("      case $command_name in")
    for command in commands:
        target = aliases.get(command, command)
        if (target,) in node_map:
            patterns = [command]
            lines.append(f"        {zsh_pattern('|'.join(patterns))}) {node_map[(target,)].function_name} ;;")
    lines.append("      esac")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("}")
    lines.append("")
    lines.append('_oooconf_main "$@"')

    return "\n".join(lines) + "\n"


def render_zsh_node(node: CompletionNode, lines: list[str]) -> None:
    child_position = len(node.path) + 1
    child_word_index = len(node.path) + 2
    value_position = child_position if not node.command.subcommands else child_position + 1
    subcommands = {name: child.description for name, child in node.command.subcommands.items()}
    lines.append(f"{node.function_name}() {{")
    lines.append("  local context state line")
    lines.append("  typeset -A opt_args")
    if subcommands:
        zsh_describe_array("subcmds", subcommands, lines)
    if node.values:
        zsh_describe_array("values", node.values, lines)
    lines.append("  _arguments -C \\")
    option_specs = []
    for option, description in node.options.items():
        option_specs.append(
            zsh_option_spec(option, description, node.completers.get(option), node.option_values.get(option))
        )
    for spec_line in option_specs:
        lines.append(f"    '{quote_zsh(spec_line)}' \\")
    if subcommands:
        lines.append(f"    '{child_position}:subcommand:->command' \\")
        lines.append("    '*::arg:->args'")
    elif node.values:
        lines.append(f"    '{value_position}:value:->value' \\")
        lines.append("    '*::arg:->args'")
    else:
        lines.append("    '*::arg:->args'")
    lines.append("")
    lines.append("  case $state in")
    if subcommands:
        lines.append("    command)")
        lines.append("      _describe -t subcommands 'oooconf subcommand' subcmds")
        lines.append("      ;;")
        lines.append("    args)")
        lines.append(f"      case $words[{child_word_index}] in")
        for child in subcommands:
            child_path = (*node.path, child)
            lines.append(
                f"        {zsh_pattern(child)}) _oooconf_{'_'.join(shell_safe_name(part) for part in child_path)} ;;"
            )
        lines.append("      esac")
        lines.append("      ;;")
    if node.values:
        lines.append("    value)")
        lines.append("      _describe -t values 'oooconf value' values")
        lines.append("      ;;")
    lines.append("  esac")
    lines.append("}")


def format_ps_array(values: list[str], indent: str = "        ") -> list[str]:
    lines: list[str] = []
    total = len(values)
    for index, value in enumerate(values):
        suffix = "," if index < total - 1 else ""
        lines.append(f"{indent}'{quote_ps(value)}'{suffix}")
    return lines


def render_ps_string_array(values: list[str]) -> str:
    return "@(" + ", ".join(f"'{quote_ps(value)}'" for value in values) + ")"


def render_ps_nodes(nodes: list[CompletionNode]) -> list[str]:
    lines = ["    $OooconfNodes = @{"]
    for node in sorted(nodes, key=lambda item: item.key):
        options = list(node.options.keys())
        values = list(node.values.keys())
        subcommands = list(node.command.subcommands.keys())
        lines.append(f"        '{quote_ps(node.key)}' = @{{")
        lines.append(f"            Options = {render_ps_string_array(options)}")
        lines.append(f"            Values = {render_ps_string_array(values)}")
        lines.append(f"            Subcommands = {render_ps_string_array(subcommands)}")
        lines.append("            OptionValues = @{")
        for option, option_values in sorted(node.option_values.items()):
            lines.append(f"                '{quote_ps(option)}' = {render_ps_string_array(list(option_values.keys()))}")
        lines.append("            }")
        lines.append("        }")
    lines.append("    }")
    return lines


def render_ps_hashtable(mapping: dict[str, str], indent: str = "    ") -> list[str]:
    lines: list[str] = [f"{indent}@{{"]
    for key in sorted(mapping.keys()):
        lines.append(f"{indent}    '{quote_ps(key)}' = '{quote_ps(mapping[key])}'")
    lines.append(f"{indent}}}")
    return lines


def render_powershell(commands: list[str], spec: CliSpec) -> str:
    commands = command_order(commands, spec)
    nodes = walk_commands(spec.commands, spec)

    lines: list[str] = []
    lines.append("# PowerShell argument completions for oooconf")
    lines.append("# Generated by scripts/generate_oooconf_completions.py; edit scripts/oooconf-cli-spec.toml instead.")
    lines.append("# This file is automatically loaded by the managed PowerShell profile via common.ps1")
    lines.append("")
    lines.append("function Get-OooconfCompletions {")
    lines.append("    param($wordToComplete, $commandAst, $cursorPosition)")
    lines.append("")
    lines.append("    $OooconfCommands = @(")
    lines.extend(format_ps_array(commands))
    lines.append("    )")
    lines.append("")
    lines.append("    $OooconfGlobalOptions = @(")
    lines.extend(format_ps_array(list(spec.global_options.keys())))
    lines.append("    )")
    lines.append("")
    lines.append("    $OooconfAliases =")
    lines.extend(render_ps_hashtable(spec.aliases()))
    lines.append("")
    lines.extend(render_ps_nodes(nodes))
    lines.append("")
    lines.append("    $elements = $commandAst.CommandElements")
    lines.append("    $tokens = @()")
    lines.append("    for ($i = 0; $i -lt $elements.Count; $i++) {")
    lines.append("        $element = $elements[$i]")
    lines.append("        if ($element -is [System.Management.Automation.Language.CommandParameterAst]) {")
    lines.append('            $val = "-$($element.ParameterName)"')
    lines.append("            if ($val -eq $wordToComplete -and $i -eq ($elements.Count - 1)) { break }")
    lines.append("            $tokens += $val")
    lines.append(
        "        } elseif ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {"
    )
    lines.append("            $val = $element.Value")
    lines.append("            if ($val -eq $wordToComplete -and $i -eq ($elements.Count - 1)) { break }")
    lines.append("            $tokens += $val")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    $commandIndex = -1")
    lines.append("    for ($i = 0; $i -lt $tokens.Length; $i++) {")
    lines.append("        if ($tokens[$i] -match '(^|[\\/])(oooconf|o)(\\.ps1|\\.cmd)?$') {")
    lines.append("            $commandIndex = $i")
    lines.append("            break")
    lines.append("        }")
    lines.append("    }")
    lines.append("    if ($commandIndex -eq -1) { return @() }")
    lines.append("")
    lines.append("    $commandName = $null")
    lines.append("    $commandPos = -1")
    lines.append("    for ($i = $commandIndex + 1; $i -lt $tokens.Length; $i++) {")
    lines.append("        $token = $tokens[$i]")
    lines.append("        if ($token -in @('-C', '--repo-root')) { $i++; continue }")
    lines.append("        if ($token -in $OooconfCommands) { $commandName = $token; $commandPos = $i; break }")
    lines.append("        if ($token -notlike '-*') { break }")
    lines.append("    }")
    lines.append("")
    lines.append("    if ($null -eq $commandName) {")
    lines.append(
        "        return ($OooconfCommands + $OooconfGlobalOptions) | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }"
    )
    lines.append("    }")
    lines.append("")
    lines.append("    if ($OooconfAliases.ContainsKey($commandName)) { $commandName = $OooconfAliases[$commandName] }")
    lines.append("    $path = @($commandName)")
    lines.append("    $nodeKey = $commandName")
    lines.append("    $lastNodeKey = $nodeKey")
    lines.append("    for ($i = $commandPos + 1; $i -lt $tokens.Length; $i++) {")
    lines.append("        $node = if ($OooconfNodes.ContainsKey($nodeKey)) { $OooconfNodes[$nodeKey] } else { $null }")
    lines.append("        if ($null -eq $node) { break }")
    lines.append("        $token = $tokens[$i]")
    lines.append("        if ($token -like '-*') { $i++; continue }")
    lines.append("        if ($token -in $node.Subcommands) {")
    lines.append("            $path += $token")
    lines.append("            $nodeKey = ($path -join ':')")
    lines.append("            $lastNodeKey = $nodeKey")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append(
        "    $currentNode = if ($OooconfNodes.ContainsKey($lastNodeKey)) { $OooconfNodes[$lastNodeKey] } else { $null }"
    )
    lines.append("    if ($null -eq $currentNode) { return @() }")
    lines.append("    $previousToken = if ($tokens.Length -gt 0) { $tokens[-1] } else { '' }")
    lines.append("    if ($currentNode.OptionValues.ContainsKey($previousToken)) {")
    lines.append("        $completions = $currentNode.OptionValues[$previousToken]")
    lines.append("    } else {")
    lines.append("        $completions = $currentNode.Options + $currentNode.Subcommands + $currentNode.Values")
    lines.append("    }")
    lines.append("")
    lines.append('    return $completions | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {')
    lines.append("        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("@('oooconf', 'oooconf.ps1', 'oooconf.cmd', 'o', 'o.ps1', 'o.cmd') | ForEach-Object {")
    lines.append("    Register-ArgumentCompleter -Native -CommandName $_ -ScriptBlock {")
    lines.append("        param($wordToComplete, $commandAst, $cursorPosition)")
    lines.append(
        "        Get-OooconfCompletions -wordToComplete $wordToComplete -commandAst $commandAst -cursorPosition $cursorPosition"
    )
    lines.append("    }")
    lines.append("}")

    return "\n".join(lines) + "\n"


def main() -> int:
    spec = load_cli_spec(CLI_SPEC_FILE, extra_definitions=load_dependency_definitions())
    commands = load_commands(COMMANDS_FILE)

    ZSH_OUTPUT.write_text(render_zsh(commands, spec), encoding="utf-8", newline="\n")
    POWERSHELL_OUTPUT.write_text(render_powershell(commands, spec), encoding="utf-8", newline="\n")

    print(f"updated: {ZSH_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"updated: {POWERSHELL_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
